cookie:
  expiry_days: 30
  key: "0DILOrtVn4MVqseXYfvzZCa3ioCIpsrBi9UDDEO2jLXe2YHEwpj1ga8LGG4XIqQeMSaK1yIAeLh590hFZmp9IMOr3ps0Vt4G8NhRQaSHyRJUF2GkVwJNVqQzoUg4dqIi"
  name: "mistralhack"

credentials:
  usernames:
    admin:
      email: admin@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: John
      last_name: Smith
      logged_in: False # Will be managed automatically
      password: abc # Will be hashed automatically
oauth2: # Optional
  google: # Follow instructions: https://developers.google.com/identity/protocols/oauth2
    client_id: # To be filled
    client_secret: # To be filled
    redirect_uri: # URL to redirect to after OAuth2 authentication